### ISSUE TITLE
Token Mismatch Exception on Login after verification

### ISSUE THREAD

**Issue by MAsifOfficial** [lubusIN/laravel-email-verification-app-boilerplate#10]
Hi!
When a user registers & then clicks the verification link, he gets redirected to login page after being verified. But when he tries to login, ToeknMismatchException is raised.

**Comment by introwit** [comment]
@MAsifOfficial 

- Your sessions are not being set properly. The CSRF token works by flashing the value to your session, then comparing the value with what was submitted with your form on the next request. If your sessions are not being set then this will always fail. 
- They are not being set properly because the directory `storage/framework/sessions` is not writable. Laravel needs the `storage` & `bootstrap\cache` dir as writable. 
- To make them writable use the following commands on *nix based OSs:

```bash
sudo chgrp -R www-data storage bootstrap/cache
sudo chmod -R ug+rwx storage bootstrap/cache
```

You can re-open the issue if the problem persists :)
